### ISSUE TITLE
Decode IP in Request

### ISSUE THREAD

**Issue by chetanch** [chobie/php-rtb-server#2]
I am unable to decode that ip which send in request, if you help on decoding part of ip 
that will be huge help for me

Thanks

**Comment by chobie** [comment]
see also

>   // The first 3 bytes of the IP address in network byte order for IPv4, or the
>  // first 6 bytes for IPv6.  Note that the number and position of the bytes
>  // included from IPv6 addresses may change later.
>  optional bytes ip = 4;

https://developers.google.com/ad-exchange/rtb/downloads/realtime-bidding-proto.txt

**Comment by chobie** [comment]
maybe this will work fine but requester requests really random number. this may incorrect actually request.

**Comment by chobie** [comment]
Hmm, could you send me actual code?

**Comment by chobie** [comment]
np. I'll check this later

**Comment by chobie** [comment]
I'm on the job now. I'll check when I back home

**Comment by chetanch** [comment]
ok np thanks for your response

**Comment by chobie** [comment]
here is the minimum generator script.
https://gist.github.com/chobie/9489e070cede0d352a7d

I run this script and output is this.

``` bash
bash-3.2$ python gen.py
id: "\336\251\333\257Fk\303\0363n0\232\254?B\r"
ip: "\327r\250"
is_test: true
bash-3.2$ cat dat | hexdump -C
00000000  12 10 de a9 db af 46 6b  c3 1e 33 6e 30 9a ac 3f  |......Fk..3n0..?|
00000010  42 0d 22 03 d7 72 a8 78  01                       |B."..r.x.|
00000019
```

at this time `22 03 d7 72 a8` is a part of `ip` field. more specifically

| bytes | detail |
| --- | --- |
| 22 | tag & wiretype |
| 03 | length (3bytes) |
| d7 72 a8 | actual data |

parsing and echo this data with minimum php file like this. we expect the output is `d7 72 a8` (this is hexadecimal expression. use `hexdump -C` and show actual bytes).

``` php
<?php
require dirname(__DIR__) . DIRECTORY_SEPARATOR . "message" . DIRECTORY_SEPARATOR . "realtime-bidding.proto.php";

$data = file_get_contents("dat");
$request = BidRequest::parseFromString($data);
/** @var $request BidRequest */

$data = $request->getIp();

echo $data;
```

the output is:

```
bash-3.2$ php dump.php | hexdump -C
00000000  d7 72 a8                                          |.r.|
00000003
```

hmm, It seems fine. I can't reproduce your problem.

the difference between python and php is output bytes expression. php just outputs actual byte sequences.
but python outputs bytes as human readable expression like `ip: "\327r\250"`. is that the difference?

**Comment by chetanch** [comment]
please execute like php dump.php  , how we can convert that value in normal ip

**Comment by chobie** [comment]
> if you print_r($request ), you will get ÌjÈ value

php doesn't care about showing binary value. just as is.
I think `ÌjÈ` same as "314j\310 ". the difference is: how to print value.

let we talk with actual code as discussing binary value in text is too hard.
at least above my code keep same value. so I think it's not a bug.

did I miss something?

**Comment by chetanch** [comment]
ok, I have convert this value using bin2hex(data). Am I doing correct?

**Comment by chobie** [comment]
No. python's byte expression is not hex code at this time. maybe it's better to compare with base64 encoded value.

**Comment by chetanch** [comment]
But I found hexdump out is matched with bin2hex(data) after that I am using that value to convert in ip  using hexToDecimal 
, do you have skype id?

**Comment by chobie** [comment]
yea. `hexdump -C` shows hex+ASCII display. so same as bin2hex(data) value.
I don't use skype usually. but I'm online as `chobi_e` now. I can support you by text.
